spring:
  jackson:
    default-property-inclusion: non_null
  datasource:
    url: jdbc:mysql://localhost:3306/paginationjunior
    username: root
    password: 0910886381018
  jpa :
    database-platform : org.springframework.orm.jpa.vendor.Database.MYSQL
    generate-ddl : true
    show-sql : true
    hibernate :
      ddl-auto : update
    properties :
      hibernate :
        globally_quoted_identifiers : true
        dialect : org.hibernate.dialect.MySQLDialect
        format_sql : true
